[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM4
monitor_port = COM4

build_flags =
    -D T5_PROFILE_ESP32=1